apiVersion: apps/v1
kind: Deployment
metadata:
  name: movecloud
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: movecloud
  template:
    metadata:
      labels:
        app: movecloud
    spec:
      containers:
      - name: jenkins
        image: takkadapelly/jenkins:latest
        ports:
        - containerPort: 9001
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
