apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-deployment-name
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
        - name: your-container-name
          image: takkadapelly/jenkins:latest # This will be replaced dynamically in the pipeline
          ports:
            - containerPort: 9001
