apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: movecloud-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: movecloud
  minReplicas: 4
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
