apiVersion: v1
kind: Service
metadata:
  name: your-service-name
  namespace: default
spec:
  type: LoadBalancer # Use LoadBalancer for external access or ClusterIP for internal
  selector:
    app: your-app
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
