apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer  # Use LoadBalancer to expose on port 9001
  ports:
    - port: 9001         # Port exposed to the outside
      targetPort: 9001   # Port on which the application is running
  selector:
    app: web
