apiVersion: v1
kind: Service
metadata:
  name: movecloud
  namespace: default
spec:
  type: LoadBalancer # Use LoadBalancer for external access or ClusterIP for internal
  selector:
    app: movecloud
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
