name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Match the Node.js version in your Dockerfile

    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test -- --watchAll=false --passWithNoTests

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensure tests are run before build and deploy

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWD }}

    - name: Build and push Docker image for ARM64 (linux/arm64)
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/arm64
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/movecloud-web:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy using SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ vars.RASP_HOST }}
        username: ${{ vars.RASP_USER }}
        password: ${{ vars.RASP_PASS }}
        port: 22
        script: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWD }}
          docker pull ${{ secrets.DOCKER_USERNAME }}/movecloud-web:latest
          docker stop movecloud-web || true
          docker rm movecloud-web || true
          docker run -d --name movecloud-web -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/movecloud-web:latest
